import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';


 export interface Client {
  _id?: string; // Optional if generated by the backend
  name: string;
  email: string;
  bussinessName: string;
  password: string;
  mobile: string;
  address: string;
  gstNumber?: string;  // Optional field
  role?: string;
  customerID?:string;
  image?:string;
}



@Injectable({
  providedIn: 'root'
})
export class ClientService {
  private apiUrl = 'http://localhost:3000/api/client'; // Replace with your actual API endpoint

  constructor(private http: HttpClient) { }

  // Method to add a new client
  addClient(clientData: Client): Observable<Client> {
    return this.http.post<Client>(`${this.apiUrl}/add`, clientData);
  }

  getClientNameAndBusiness(customerID: string): Observable<{ name: string, bussinessName: string }> {
    return this.http.get<{ name: string, bussinessName: string }>(`${this. apiUrl }/client-name-business?customerID=${customerID}`);
  }

  // Method to get all clients
  getClients(): Observable<Client[]> {
    return this.http.get<Client[]>(`${this.apiUrl}/getall`);
  }


  deleteClient(clientId: string): Observable<void> {
    return this.http.post<void>(`${this.apiUrl}/remove`, { id: clientId });
  }


  register(client: Client): Observable<Client> {
    return this.http.post<Client>(`${this.apiUrl}/register`, client);
  }
  login(password: string, email?: string, mobile?: string, customerID?: string): Observable<any> {
    const url = `${this.apiUrl}/login`;
    const body: any = { password };

    if (email) {
      body.email = email;
    } else if (mobile) {
      body.mobile = mobile;
    } else if (customerID) {
      body.customerID = customerID;
    }

    return this.http.post<any>(url, body);
  }


  getClientData(clientIds: string[]): Observable<any[]> {
    return this.http.post<any[]>(`${this.apiUrl}/clients`, { clientIds });
  }
  getClientDetails(id: string): Observable< Client> {
    // Send GET request with ID in the URL
    return this.http.get< Client>(`${this.apiUrl}/details?id=${id}`);
  }


  updateClientPassword(id: string, updateData: { password: string }): Observable<any> {
    return this.http.post(`${this.apiUrl}/update?id=${id}`, updateData);
  }


  private apiUrl1 = 'http://localhost:3000/api/PasswordResetRequest';
  requestPasswordReset(clientId: string): Observable<void> {
    return this.http.post<void>(`${this.apiUrl1}/password-reset`, { id: clientId });
  }


  getAllResetRequests(): Observable<any> {
    return this.http.get<any>(`${this.apiUrl1}/getAll`);
  }


  markPasswordUpdated(clientId: string): Observable<any> {
    return this.http.patch<any>(`${this.apiUrl1}/status`, { clientId });
  }
  getClientforInvoice(customerID: string): Observable<any> {
    return this.http.get(`${this.apiUrl}/invoice-details/${customerID}`);
  }



  private apiUrl2 = 'http://localhost:3000/api/client';

  passwordresetRequest(email?: string, mobile?: string, customerID?: string): Observable<any> {
    const url = `${this.apiUrl2}/password-resetRequest-Details`;
    const body: any = {};

    if (email) {
      body.email = email;
    } else if (mobile) {
      body.mobile = mobile;
    } else if (customerID) {
      body.customerID = customerID;
    } else {
      throw new Error('At least one of email, mobile, or customerID must be provided.');
    }

    return this.http.post<any>(url, body);
  }

  private apiUrl4 = 'http://localhost:3000/api/client';

  uploadFile(file: File, clientId: string): Observable<any> {
    const formData: FormData = new FormData();
    formData.append('file', file); // Append the file to formData

    // Make POST request to the upload endpoint
    return this.http.post(`${this. apiUrl4}/upload/${clientId}`, formData);
  }


  getFileUrls(customerId: string): Observable<any> {
    const url = `${this.apiUrl4}/files/${customerId}`;
    return this.http.get<any>(url);
  }
}
