import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';

export interface Driver {
  _id?: string; // Optional if generated by the backend
  name: string;
  email: string;
  password: string;
  mobile: string;
}
@Injectable({
  providedIn: 'root'
})
export class DriverService {

  private apiUrl = 'http://localhost:3000/api/driver'; // Replace with your actual API endpoint

  constructor(private http: HttpClient) { }

  // Method to add a new client
  addDriver(clientData: Driver): Observable<Driver> {
    return this.http.post<Driver>(`${this.apiUrl}/add`, clientData);
  }


  // Method to get all clients
  getDriver(): Observable<Driver[]> {
    return this.http.get<Driver[]>(`${this.apiUrl}/getall`);
  }


  deleteDriver(clientId: string): Observable<void> {
    return this.http.post<void>(`${this.apiUrl}/remove`, { id: clientId });
  }




}
